### ISSUE TITLE
drag event

### ISSUE THREAD

**Issue by bystrovsv** [philip-brink/DragAndDropLists#8]
Great library.
Can you please tell me if it is possible to intercept the drag and drop event?
I want to display the position deletion area when starting dragging.
Saw wrappers, but did not understand how to use it.

**Comment by philip-brink** [comment]
Hi @bystrovsv glad you like it.

Currently the only methods accessible to the outside are are the add and reorder functions. I'm open to adding more of course as long as they don't make the standard use cases more complicated.

For your case, do you mean something like shown here?

![reorder_placeholder](https://user-images.githubusercontent.com/6272888/94845024-13d83100-03ed-11eb-9b55-aaf238ac4587.gif)

**Comment by bystrovsv** [comment]
Not really.
I would like to see multiple drag targets. When dragging to them, the list item should be deleted. So that you can set several different statuses when deleting. For example, deleted with the status "Success", deleted with the status "Failed", just deleted.
And place of the target want to be arbitrary

**Comment by philip-brink** [comment]
Hi @bystrovsv, I've added a few options in version 0.2.2 that might be helpful for you.

You can now specify the acceptance criteria for where a list or item can be dropped, you can use the parameters `listOnWillAccept`, `listTargetOnWillAccept`, `itemOnWillAccept` and `itemTargetOnWillAccept` in `DragAndDropLists`.

I've also added a more direct way to access the objects *after* they have been accepted, and you can decide to do whatever you'd like with those as DragAndDropLists doesn't do any reordering internally (ie you can simply do nothing when `onItemReorder` or `onListReorder` are called). For these, you can use the parameters `listOnAccept`, `listTargetOnAccept`, `itemOnAccept` and `itemTargetOnAccept` in `DragAndDropLists`.

Let me know if that helps!

**Comment by bystrovsv** [comment]
Great, but I don't know how to apply it.
I found the behavior I wanted in the Flutter BoardView.
As you drag a item, targets appear to which you can drag the item. Then it is removed from the list.
Can this be done with the current set of capabilities?

**Comment by philip-brink** [comment]
Hi @bystrovsv, this depends on exactly what you would need to do, and is probably a bit outside of the scope for this project.

If you want to be able to drag items *within* the lists, with an *option* to drag outside of the list into some other container, then yes, this is likely possible though I have not tested it. You would need to add a `DragAndDropListTarget` or `DragAndDropItemTarget` somewhere outside of the list hierarchy, and you can drag your list/item to those targets, and remove the item from the list through the methods I listed earlier.

If you want to prevent all reordering *within* the list but want to be able to drag an item out of the list into some other target, you would need to set the `listOnWillAccept` and `itemOnWillAccept` to always return false. Then as in the previous case, set some targets outside of the list hierarchy, and their `listOnWillAccept` and `itemOnWillAccept` should return true.

It may also be easier to just make your own targets, as `DragAndDropListTarget` or `DragAndDropItemTarget` both require a list of parameters (`DragAndDropBuilderParameters`) that is auto generated for internal use by the `DragAndDropLists` widget. You would need `DragTarget<DragAndDropListInterface>` and/or `DragTarget<DragAndDropItem>` widgets, and you can control them as you like.

You will likely also need to set the parameter `constrainDraggingAxis` (added in v 0.2.5) to false in order to freely drag lists/items to widgets outside of the `DragAndDropLists` widget.

**Comment by bystrovsv** [comment]
Thanks a lot, I'll try

**Comment by bystrovsv** [comment]
I only want to visualize a target when i start dragging a item.
How to do it? I need event.

**Comment by philip-brink** [comment]
In 0.2.7 I now added `onItemDraggingChanged` and `onListDraggingChanged` parameters to `DragAndDropLists`. You can supply methods to these parameters that will be called when the dragging starts and when it ends.

**Comment by bystrovsv** [comment]
1. When I define onItemDraggingChanged, I cannot move item to lists. So conceived?
2. I don't understand how I can remove the item of the original list. It cannot be defined via DragAndDropItem. Need item index and list index, how in onItemReorder.

**Comment by philip-brink** [comment]
When an item or list is dropped onto a target, it calls the `onItemReorder` or `onListReorder`, and provides the indices of the item/list being dragged. If you want to delete the item/list instead of reordering it, you just need to remove it from the list.

To do so, you need to modify your list, using whatever state manager you use in your project (ie setState for pure flutter, or modifications to the lists in bloc, mobx, etc). DragAndDropLists will just reflect what is currently in the list.

**Comment by bystrovsv** [comment]
I understand. But onItemReorder does not work when item dragging to external target. What can be done?

**Comment by philip-brink** [comment]
Using flutter's [DragTarget](https://api.flutter.dev/flutter/widgets/DragTarget-class.html) you need to have at least the following methods defined:
* `onWillAccept` (whether or not you will allow the item to be dropped)
* `onAccept` (the item has been dropped, what to do with it?)

In your case, when onAccept is called, you will get a reference to the incoming object from onAccept. If it is a list item from DragAndDropLists, it will be of type `DragAndDropItem` , and if it is a list it will be of type `DragAndDropListInterface`. Once you have that reference, you can search your list for that object, and delete it.

**Comment by bystrovsv** [comment]
Yes, that's what I do.
But DragAndDropItem does not contain information about the original data object. And it is the data object that needs to be deleted, not the widget.
I tried to override the whole chain - lists, list, item. I wanted to add a reference to the original object in the item.
I was unable to achieve the result

**Comment by bystrovsv** [comment]
Probably, I need to determine the deleted element of the original data through the index of the DDitem in the DDlist ... Right?

**Comment by philip-brink** [comment]
Yes, there are a few ways to do this:
1. Create your list of `DragAndDropList` and all its contents outside of your `DragAndDropLists` widget. You can check the basic example included in the package to see that. Then you could just do an object comparison to find which is the right DragAndDropItem to delete.
2. Create a class that extends `DragAndDropItem` and add some tag or key element that you can compare to your original list. If only items will be deleted this way, you won't need to create any other subclasses.
3. You could use the same list index and item index as you suggested, if you maintain your data list in the same order as what will be used by DragAndDropLists

**Comment by bystrovsv** [comment]
Thanks. I do 3
All work.
